# -*- coding: utf-8 -*-
"""ASSIGNMENT 3: Module 4: Functions & Modules in Python .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toacHPMw6nQy0wiHmHyeoHIDAiFbBcB_
"""



def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Sample call to the function
sample_number = int(input("Enter a number: "))
output = factorial(sample_number)

# Print the result
print(f"The factorial of {sample_number} is {output}")

import math

# Ask the user for a number
number = float(input("Enter a number: "))

# Perform calculations using math module
square_root = math.sqrt(number)
natural_log = math.log(number)
sine_value = math.sin(number)  # Input is in radians

# Display the results
print(f"Square root of {number} is: {square_root}")
print(f"Natural logarithm (log base e) of {number} is: {natural_log}")
print(f"Sine of {number} radians is: {sine_value}")